version: "3.7"
services:

  postgres:
    image: postgres:14.5
    container_name: postgres
    pull_policy: if_not_present
    restart: unless-stopped
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    networks:
      - default
  urlshorter:
    container_name: urlshorter
    image: jkaninda/urlshorter:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - URL_LENGHT=4
      - DOMAIN_URL=http/localhost:8080
    tty: true
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - default
